### ISSUE TITLE
Scary looking unreadable notice on start

### ISSUE THREAD

**Issue by YoukaiTheGit** [tommaier123/NoodleManagerX#1] opened 2022-02-06 21:12 UTC
Upon first running NoodleManagerX v0.5.0, I'm greeted with this notice:
![image](https://user-images.githubusercontent.com/75144814/152701507-a1793293-c8d3-4aaf-9646-53e643ef9b27.png)

It appears to say "All maps ?????? deleted".  I'm afraid.

**Comment by tommaier123** [comment] 2022-02-06 22:25
Very interesting. Probably something to do with system fonts. I'll try forcing it to use the embedded font.

**Comment by YoukaiTheGit** [comment] 2022-02-06 23:22
I do have the Windows 10  "Display Settings > Scale and Layout > Size of text/apps/items" set to 125%.  Possibly changing assumptions about how large the font will render?

**Comment by tommaier123** [comment] 2022-02-06 23:45
Looking at your other screenshot the dialog looks correct. The problem is that the first warning dialog is not opened in the context of the main window.

**Comment by tommaier123** [comment] 2022-02-06 23:57
Can you try [this one](https://drive.google.com/drive/folders/1HR4ZdDTU5lNp1Ou_dcAecCCKOuzvoGSX?usp=sharing) and see if it is fixed? You can trigger the initial cleanup by adding a / to the Synth Riders path in the settings.

**Comment by YoukaiTheGit** [comment] 2022-02-07 00:05
requested access as WhazzItToYa

**Comment by tommaier123** [comment] 2022-02-07 00:32
Sorry, I thought it wad set up so everyone has access. Should be good now.

**Comment by YoukaiTheGit** [comment] 2022-02-07 00:36
Opening the new app, going to settings & adding the extra '\' produced a reasonable looking dialog:

![image](https://user-images.githubusercontent.com/75144814/152708640-7af4cfa7-eedd-4101-b8cc-b899fba8377e.png)

**Comment by tommaier123** [comment] 2022-02-07 00:41
Great. Thanks for testing

**Comment by YoukaiTheGit** [comment] 2022-02-07 01:03
Ahh, I just did another test meant to simulate the "first time" experience as I originally reported, and that dialog is still messed up.

Steps:
1. With the app closed, deleted the %appdata%/NoodleManagerX/Settings.json file
2. Ran NoodleManagerX (the experimental version linked above)

Got  
![image](https://user-images.githubusercontent.com/75144814/152709863-503bbcbe-73ae-4fee-ae1a-823d288838ae.png)

**Comment by YoukaiTheGit** [comment] 2022-02-07 01:10
Did some more testing, and the behavior is random: With settings.json deleted, I opened & closed the app multiple times (selecting 'cancel' in the warning dialog each time, which doesn't appear to create a settings.json file).  Most of the time, the dialog looks normal, but occasionally it comes up with the large font.

**Comment by tommaier123** [comment] 2022-02-07 08:58
I updated the experimental version. This time it uses the embedded font. If that doesn't fix it I'm out of ideas.

**Comment by YoukaiTheGit** [comment] 2022-02-07 18:26
I redownloaded the app from the same link as above & tested.  Problem still occurs intermittently on startup.

**Comment by tommaier123** [comment] 2022-02-07 19:10
Ok, thanks for testing. I'll let you know when I think of something else to try.

**Comment by tommaier123** [comment] 2022-03-16 11:04
Fixed in full release

**Closed by tommaier123** 2022-03-16 11:04 UTC
